# Estágio 1: build do Angular
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --no-audit --no-fund || npm install --no-audit --no-fund
COPY . .
RUN npm run build

# Estágio 2: Nginx sem root (escuta na porta 8080)
FROM nginxinc/nginx-unprivileged:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/sre-dashboard-frontend/browser /usr/share/nginx/html
EXPOSE 8080
